site_name: '矽谷牛的耕田筆記'
copyright: Copyright &copy; 2019 - 2020 technologynoteniu
theme:
  custom_dir: overrides
  icon:
    logo: material/bookshelf
  font:
    text: Noto Sans TC
  language: zh-TW
  name: material
  palette:
    primary: teal
    scheme: preference
nav:
  - Home: README.md
  - Kubernetes:
      - Introduction: kubernetes/introduction.md
      - CI/CD: kubernetes/cicd.md
      - Network: kubernetes/network.md
      - Observability: kubernetes/observability.md
      - Service Mesh: kubernetes/service-mesh.md
      - Use Case: kubernetes/usecase.md
      - Tools: kubernetes/tool.md
  - Linux:
      - Network: linux/network.md
      - Container: linux/container.md
      - Tool: linux/tool.md
  - Infrastructure as Code:
      - Terraform: iac/terraform.md
  - Personal Donation: donations.md
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/technologynote
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/technologynoteniu
    - icon: fontawesome/brands/github
      link: https://github.com/technologynoteniu
